### ISSUE TITLE
docker: Error response from daemon: Head "https://ghcr.io/v2/rollkit/local-celestia-devnet/manifests/main": unauthorized.

### ISSUE THREAD

**Issue by jcstein** [rollkit/local-celestia-devnet#21]
```bash
# in
docker run --platform linux/amd64 -p 26657:26657 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet

# out
Unable to find image 'ghcr.io/rollkit/local-celestia-devnet:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/rollkit/local-celestia-devnet/manifests/latest": unauthorized.
See 'docker run --help'.
```

```bash
# in
docker run --platform linux/amd64 -p 26657:26657 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet:4fa5220

# out
Unable to find image 'ghcr.io/rollkit/local-celestia-devnet:4fa5220' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/rollkit/local-celestia-devnet/manifests/4fa5220": unauthorized.
See 'docker run --help'.
```

```bash
# in
docker run --platform linux/amd64 -p 26657:26657 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet:main

# out
Unable to find image 'ghcr.io/rollkit/local-celestia-devnet:main' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/rollkit/local-celestia-devnet/manifests/main": unauthorized.
See 'docker run --help'.
```

**Comment by smuu** [comment]
Package is private
![image](https://user-images.githubusercontent.com/18609909/230423603-52ec3c72-2511-41d9-ba3f-080ca96959b0.png)

Also, there is currently no `latest` or `main` tag.
https://github.com/rollkit/local-celestia-devnet/pkgs/container/local-celestia-devnet/versions?filters%5Bversion_type%5D=tagged

**Comment by jcstein** [comment]
got it. thanks! it didn't work with this either

```bash
# in
docker run --platform linux/amd64 -p 26657:26657 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet:4fa5220

# out
Unable to find image 'ghcr.io/rollkit/local-celestia-devnet:4fa5220' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/rollkit/local-celestia-devnet/manifests/4fa5220": unauthorized.
See 'docker run --help'.
```

**Comment by jcstein** [comment]
I don't know what to do to tag versions, could you please help add `latest` and `main` tags?

**Comment by Bidon15** [comment]
we don't have latest/main tags for reasons that we need to follow semantic versioning node is having 
let's cut a release v0.8.2 for local-devnet 

wdyt? @jcstein

**Comment by MSevey** [comment]
the private vs public package issue should be fixed. this was a rollkit org level update to match celestia.

You might need to recreate the package

**Comment by jcstein** [comment]
how do we cut a release on this @Bidon15? I'm hoping to so I can update:
https://github.com/celestiaorg/docs/pull/629
https://github.com/rollkit/docs/pull/162
https://github.com/rollkit/local-celestia-devnet/pull/20

**Comment by smuu** [comment]
> how do we cut a release on this @Bidon15? I'm hoping to so I can update: [celestiaorg/docs#629](https://github.com/celestiaorg/docs/pull/629) [rollkit/docs#162](https://github.com/rollkit/docs/pull/162) #20

I cut a release on v0.8.2.

**Comment by jcstein** [comment]
thank you 😄
