### ISSUE TITLE
Generate token for RPC auth

### ISSUE THREAD

**Issue by tzdybal** [rollkit/local-celestia-devnet#32]
To fully use celestia-node RPC, token has to be [generated and saved in environment variable](https://docs.celestia.org/developers/rpc-tutorial/#auth-token).

This step is missing from current entrypoint script.

**Comment by nashqueue** [comment]
Tracked by https://github.com/rollkit/celestia-openrpc/issues/20

**Comment by nashqueue** [comment]
Tracking issue is closed
