### ISSUE TITLE
image failed to build

### ISSUE THREAD

**Issue by jcstein** [rollkit/local-celestia-devnet#54]
### Version of Git SHA

last PR

### System OS

github issue

### Steps to reproduce it

https://github.com/rollkit/local-celestia-devnet/actions/runs/5575848126

### Expected result

action builds image for ghcr

### Actual result

https://github.com/rollkit/local-celestia-devnet/actions/runs/5575848126

**Comment by jcstein** [comment]
still facing issue
https://github.com/rollkit/local-celestia-devnet/issues/56 (closed this though as duplicate)

**Comment by Bidon15** [comment]
@jcstein can we close this? seems to be working afaict
