### ISSUE TITLE
bridge node panic on v0.11.0-rc11

### ISSUE THREAD

**Issue by jcstein** [rollkit/local-celestia-devnet#60]
### Version of Git SHA

https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.11.0-rc11

### System OS

macOS

### Steps to reproduce it

# Run local-celestia-devnet:

```bash
docker run --platform linux/amd64 -p 26657:26657 -p 26658:26658 -p 26659:26659 ghcr.io/rollkit/local-celestia-devnet:v0.11.0-rc11
```

# Clone Polaris:

```bash
git clone https://github.com/gupadhyaya/polaris.git
cd polaris
git checkout polaris
```

# Set auth token:
i’m using this as auth token, on rc11 devnet, but still getting same errors. ive manually set auth token and gotten same result

```bash
export AUTH_TOKEN=$(docker exec $(docker ps -q)  celestia bridge --node.store /bridge  auth admin)
```

Or change polaris/cosmos/init.sh AUTH_TOKEN to `AUTH_TOKEN=$(docker exec $(docker ps -q)  celestia bridge --node.store /bridge  auth admin)`

Or set it manually so that `AUTH_TOKEN="stringauthtoken"`

# Run polaris

```bash
mage start
```

### Expected result

posts to DA without an issue

### Actual result

https://gist.github.com/jcstein/722600b3c210f642dc1fe4635f837983 - devnet errors
https://app.warp.dev/block/11BIRPSaovIA0NkK7a6yqp - polaris errors

### Notes

[Full logs here](https://app.warp.dev/block/YBkI5zkSA3HXnfPpHqqFOd)

**Comment by renaynay** [comment]
```
panic: could not create directory "": mkdir : no such file or directory
```

Check your scripts

**Comment by Bidon15** [comment]
I think it's something wrong with how we start celestia-app 😿 
I can look into this later 🖖

**Comment by jcstein** [comment]
same here. i just revisited this.

running a rollkit x polaris rollup is how i was using the devnet, so i tried running polaris on top of rc11 and ran it with no issues, however, i still see the errors

[logs from devnet
](https://app.warp.dev/block/NlnAYBj4NSiT2MnBSoLG4j)
[logs from rollkit*polaris rollup](https://app.warp.dev/block/fIvF6yM0WmXfVxJPmE7Umt)

**Comment by Bidon15** [comment]
There are 2 issues I found so far: 

## EVM Address

```sh
Genesis transaction written to "/home/celestia/.celestia-app/config/gentx/gentx-2f5a058f314c8c5eb44c049b55aad75802a19a2d.json"
/opt/entrypoint.sh: line 16: //--evm-address: No such file or directory
```

First, we need to make sure the evm-address is used or not in our opt 


## Home dir

It's changed to `home/celestia` by default rn due to 10001 user group change 

```sh
rm: can't stat '/root/.celestia-app': Permission denied
```

Fixing them in #61 makes the local-devnet working again

**Comment by jcstein** [comment]
thank you for looking into this and pulling out the context. going to take a look at the PR!
