### ISSUE TITLE
Ctrl+c doesn't exit devnet

### ISSUE THREAD

**Issue by rootulp** [rollkit/local-celestia-devnet#65]
## Context

I just a local devnet with the steps at https://github.com/rollkit/local-celestia-devnet#to-build-and-run-the-docker-image

## Problem

I'm attempting to stop the devnet with Ctrl + C but that's not stopping the devnet. Notice the ^C in the terminal output:

```
^C7:57PM INF Timed out dur=10993.078792 height=14 module=consensus round=0 step=1
7:57PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"E3F0A48B96D9A48236EEECD0CA5D7B312F47620787844A13185BA1F51926E4A3","parts":{"hash":"653454D2A26B2FDF64CFEA23EC46B49F25F6F225545DB7ECA96B8756C402D587","total":1}},"height":14,"pol_round":-1,"round":0,"signature":"HvyIDuTbr/dftdMAaPkorWU/G+t+f4DVA1XErc1+0WuYXqCIrx1E6KaY7t/UWAFiMkMmW/SufCjdQxTc6rinAA==","timestamp":"2023-09-19T19:57:35.175358293Z"}
7:57PM INF received complete proposal block hash=E3F0A48B96D9A48236EEECD0CA5D7B312F47620787844A13185BA1F51926E4A3 height=14 module=consensus
```

To resolve I had to open Docker Dashboard and stop the container with 

<img width="1476" alt="Screenshot 2023-09-19 at 3 57 24 PM" src="https://github.com/rollkit/local-celestia-devnet/assets/3699047/4e8861ce-45fd-4da5-b144-0acdac996481">

## Question

Is this expected behavior? Is it possible for the devnet to stop if I Ctrl+C in terminal?

**Comment by nashqueue** [comment]
This was desirable in the interim because we were printing out the Auth token and copying it from the logs. Not sure if that is still necessary, as we can extract it from docker through a command now. cc  @jcstein

**Comment by jcstein** [comment]
I think being able to stop it is useful with CTRL+C. however, it is also useful to be able to keep the container running if you exit the terminal. so, if being able to stop with CTRL+C doesn't also stop the container when you exit the terminal I think the PR is desirable

**Comment by smuu** [comment]
> I think being able to stop it is useful with CTRL+C. however, it is also useful to be able to keep the container running if you exit the terminal. so, if being able to stop with CTRL+C doesn't also stop the container when you exit the terminal I think the PR is desirable

If you want to run a container in the background (no opened terminal required), use the parameter `-d`. You can still get the logs with `docker logs ...` and attach a terminal to a running container using `docker attach ...`.

**Comment by jcstein** [comment]
thanks for this issue @rootulp - it's much nicer to be able to stop the devnet with ctrl+c than using dashboard or something janky like `docker stop $(docker ps -aq)`
