### ISSUE TITLE
[Feature Request]: support celestia-da

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/local-celestia-devnet#74]
### Implementation ideas

For projects integrating with local celestia devnet, it would be great to have `celestia-da` embedded into the docker image, so that integrations don't have to run another process for the gRPC DA service.

**Comment by nashqueue** [comment]
That's a very cool idea. Should we not do that in celestia-da instead of local celestia devnet ? I.E a version that you can configure to run locally?

**Comment by nashqueue** [comment]
just saw the pr and I like it
